--- 
- name: Creates .kube directory
  file:
    path: /{{ serviceAccount }}/.kube
    state: directory
    owner: "{{ serviceAccount }}"
    group: "{{ serviceAccount }}"
    recurse: yes

- name: Setup kubeconfig for serviceaccount user
  command: cp -i /etc/kubernetes/admin.conf /{{ serviceAccount }}/.kube/config